# Generated by Django 4.2.4 on 2023-09-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendvideos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootstrapTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorialVid', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='CssTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorialVid', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='HtmlTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorialVid', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='JavaScriptTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorialVid', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='ReactTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorialVid', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.DeleteModel(
            name='VideoTutorial',
        ),
    ]
