# Generated by Django 4.2.4 on 2023-09-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendvideos', '0002_bootstraptutorial_csstutorial_htmltutorial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstraptutorial',
            name='tutorialTopic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='csstutorial',
            name='tutorialTopic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='htmltutorial',
            name='tutorialTopic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='javascripttutorial',
            name='tutorialTopic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='reacttutorial',
            name='tutorialTopic',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
