# Generated by Django 4.2.4 on 2023-09-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendvideos', '0003_bootstraptutorial_tutorialtopic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstraptutorial',
            name='tutorialVid',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='csstutorial',
            name='tutorialVid',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='htmltutorial',
            name='tutorialVid',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='javascripttutorial',
            name='tutorialVid',
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reacttutorial',
            name='tutorialVid',
            field=models.URLField(max_length=255),
        ),
    ]
