# Generated by Django 4.2.4 on 2023-09-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendvideos', '0004_alter_bootstraptutorial_tutorialvid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bootstraptutorial',
            name='tutorialTopic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='csstutorial',
            name='tutorialTopic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='htmltutorial',
            name='tutorialTopic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='javascripttutorial',
            name='tutorialTopic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reacttutorial',
            name='tutorialTopic',
            field=models.CharField(max_length=200),
        ),
    ]
