# Generated by Django 4.2.4 on 2023-09-27 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendvideos', '0005_alter_bootstraptutorial_tutorialtopic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootstraptutorial',
            name='tutorialTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='csstutorial',
            name='tutorialTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='htmltutorial',
            name='tutorialTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='javascripttutorial',
            name='tutorialTime',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reacttutorial',
            name='tutorialTime',
            field=models.IntegerField(default=0),
        ),
    ]
