# Generated by Django 4.2.4 on 2023-09-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendusers',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frontendusers',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='frontendusers',
            name='otherName',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
