# Generated by Django 4.2.4 on 2023-09-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontendusers', '0002_frontendusers_dateofbirth_frontendusers_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendusers',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='frontendusers',
            name='otherName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
